server:
  port: 9090
security:
  oauth2:
    client:
      client-id: 298123968436738
      client-secret: 89e418e2586d5245c2c1e931ffc2e3da
      access-token-uri: https://graph.facebook.com/v10.0/oauth/access_token
      user-authorization-uri: https://www.facebook.com/dialog/oauth
      token-name: oauth_token
      authenticationScheme: query
      client-authentication-scheme: form
    resource:
      user-info-uri: https://graph.facebook.com/me